Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,20 +1,37 @@
 
    
 # Test
-name: Event
+name: Test
 
 on:
   # Manual trigger for testing.
   workflow_dispatch:
 
 jobs:
-  run:
+  job1:
     runs-on: ubuntu-latest
     steps:
-      - name: Event
+      - run: echo "job1"
+  job2:
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "job2"
+  job3:
+    runs-on: ubuntu-latest
+    steps:
+      - run: exit 1
+  final:
+    needs: [job1, job2, job3]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Test
         run: |
-         echo "${{ github.event_name }}"
-         echo "event_name==workflow_dispatch? ${{ github.event_name == 'workflow_dispatch' }}"
-         if [ ${{ github.event_name == 'workflow_dispatch' }} == "true" ]; then
-           echo "Matched true"
-         fi
+          if [ "${{ needs.job1.result}}" == "success" ]; then
+            echo "Job 1 success"
+          fi
+          if [ "${{ needs.job1.result}}" == "success" && "${{ needs.job3.result}}" != "success" ]; then
+            echo "Job 1 success but job 3 failed"
+          fi
+          echo "finalized"
+    
